# Generated by Django 2.1.1 on 2018-10-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ap_los', models.CharField(blank=True, max_length=500)),
                ('onds', models.CharField(blank=True, max_length=500)),
                ('bfm_template_1', models.TextField(blank=True, null=True)),
                ('bfm_template_2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bfm_rs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bfm_file', models.FileField(upload_to='bfm_app/static/bfm_app/bfm_rs_xml')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bfm_rs_df', models.FileField(blank=True, upload_to='bfm_app/static/bfm_app/bfm_rs_df')),
            ],
        ),
        migrations.CreateModel(
            name='bfm_rs_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rph', models.IntegerField()),
                ('bfm_rs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfm_app.bfm_rs')),
            ],
        ),
        migrations.CreateModel(
            name='mfv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('xml_file', models.FileField(upload_to='bfm_app/static/bfm_app/mfv_xml')),
            ],
        ),
    ]
