# Generated by Django 2.1.1 on 2018-10-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchmark',
            old_name='ap_los',
            new_name='ap',
        ),
        migrations.AddField(
            model_name='benchmark',
            name='los',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
