# Generated by Django 3.0.3 on 2020-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisapp',
            name='df_path',
            field=models.FileField(default='tat', upload_to='static/dashboard/dataframes'),
            preserve_default=False,
        ),
    ]
