# Generated by Django 3.0.3 on 2020-06-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origins', models.CharField(blank=True, max_length=50)),
                ('destinations', models.CharField(blank=True, max_length=50)),
                ('dates', models.CharField(blank=True, max_length=50)),
                ('options_in_cache', models.IntegerField(blank=True, default=0)),
                ('observations', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_carrier', models.CharField(blank=True, max_length=2)),
                ('flight_numbers', models.CharField(blank=True, max_length=200)),
                ('departure_airports', models.CharField(blank=True, default='SGV', max_length=3)),
                ('arrival_airports', models.CharField(blank=True, default='SGV', max_length=3)),
                ('departure_times', models.CharField(blank=True, default='12:00', max_length=5)),
                ('arrival_times', models.CharField(blank=True, default='12:00', max_length=5)),
                ('departure_dates', models.CharField(blank=True, default='31-MAR-2021', max_length=100)),
                ('arrival_dates', models.CharField(blank=True, default='31-MAR-2021', max_length=100)),
                ('carriers', models.CharField(blank=True, default='YY', max_length=2)),
                ('itinerary_origin', models.CharField(blank=True, max_length=3)),
                ('itinerary_destination', models.CharField(blank=True, max_length=3)),
                ('itinerary_departure_time', models.CharField(blank=True, max_length=5)),
                ('itinerary_arrival_time', models.CharField(blank=True, max_length=5)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_price', models.FloatField(default=0.0)),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ota.Search')),
            ],
        ),
    ]
