# Generated by Django 3.0.3 on 2020-06-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origins', models.CharField(blank=True, max_length=50)),
                ('destinations', models.CharField(blank=True, max_length=50)),
                ('dates', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
