# Generated by Django 3.0.3 on 2020-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
