# Generated by Django 3.0.3 on 2020-06-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_carrier', models.CharField(blank=True, max_length=2)),
                ('itinerary_origin', models.CharField(blank=True, max_length=3)),
                ('itinerary_destination', models.CharField(blank=True, max_length=3)),
                ('itinerary_departure_time', models.CharField(blank=True, max_length=5)),
                ('itinerary_arrival_time', models.CharField(blank=True, max_length=5)),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ota.Search')),
            ],
        ),
    ]
