# Generated by Django 3.0.3 on 2020-06-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0002_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='flights',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
