# Generated by Django 3.0.3 on 2020-06-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0002_auto_20200608_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='hits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
