# Generated by Django 3.0.3 on 2020-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0003_itinerary_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='observations',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='search',
            name='options_in_cache',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
