# Generated by Django 3.0.3 on 2020-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0003_search_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='cheapest_price',
            field=models.FloatField(default=999999),
        ),
    ]
