# Generated by Django 3.0.3 on 2020-06-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0004_auto_20200607_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='options_in_cache',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
