# Generated by Django 3.0.3 on 2020-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0005_auto_20200607_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='flights',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='arrival_airports',
            field=models.CharField(blank=True, default='SGV', max_length=3),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='arrival_times',
            field=models.CharField(blank=True, default='12:00', max_length=5),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='carriers',
            field=models.CharField(blank=True, default='YY', max_length=2),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='departure_airports',
            field=models.CharField(blank=True, default='SGV', max_length=3),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='departure_times',
            field=models.CharField(blank=True, default='12:00', max_length=5),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='flight_numbers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
