# Generated by Django 3.0.3 on 2020-06-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0007_auto_20200611_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='surname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='adt',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='search',
            name='cnn',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='inf',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
