# Generated by Django 3.0.3 on 2020-06-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0009_auto_20200612_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='bags',
            field=models.CharField(blank=True, default='na', max_length=50),
        ),
    ]
