# Generated by Django 3.0.3 on 2020-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0010_itinerary_bags'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='travel_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
