# Generated by Django 3.0.3 on 2020-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0011_itinerary_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='quickest_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
