# Generated by Django 3.0.3 on 2020-06-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0013_auto_20200616_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='flight_count',
            field=models.CharField(default='2,2', max_length=50),
        ),
    ]
