# Generated by Django 3.0.3 on 2020-05-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='new_url',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='original_url',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
