# Generated by Django 3.0.3 on 2020-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='encoded_url',
            field=models.URLField(default='www.google.com'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
